### ISSUE TITLE
don't use absolute path for Excel sheet

### ISSUE THREAD

**Issue by thomascastleman** [rcastleman/monte_carlo#1]
https://github.com/rcastleman/monte_carlo/blob/9974a6d7f6bdb00314440965b688b24fb17d4e1c/monte_carlo_python.py#L73

Can probably be replaced with
```python
book = xw.Book('Portfolio_monte_carlo.xlsx')
```
and it will look for a sheet so named in the current directory. This makes it easier for others to run since they won't have the same absolute paths as you.

**Comment by rcastleman** [comment]
Thank you @thomascastleman !

**Comment by rcastleman** [comment]
Fixed
