### ISSUE TITLE
use different names where necessary

### ISSUE THREAD

**Issue by thomascastleman** [rcastleman/monte_carlo#2]
https://github.com/rcastleman/monte_carlo/blob/9974a6d7f6bdb00314440965b688b24fb17d4e1c/monte_carlo_python.py#L75-L84

`results` is defined as one of the sheets on the top line, and then redefined as a list below. If you need to be able to access both of these things, they should probably have separate names.

**Comment by rcastleman** [comment]
great catch - thanks.  I renamed the sheet variable "output_results" and then checked to make sure it wasn't referenced elsewhere (it wasn't)
