### ISSUE TITLE
function should take in only what varies across calls

### ISSUE THREAD

**Issue by thomascastleman** [rcastleman/monte_carlo#3]
https://github.com/rcastleman/monte_carlo/blob/9974a6d7f6bdb00314440965b688b24fb17d4e1c/monte_carlo_python.py#L89-L99

This function (which runs one round of simulation) should only take in as inputs things which will vary across each round of simulation. Everything else can be defined above at the top level. 

For instance, I don't think the `fund_size` changes across each round, so it can be lifted out. This will make this function signature a bit clearer as to what things change / what don't.

**Comment by rcastleman** [comment]
Ah, okay.  I didn't understand that only things that vary need to be put in the argument list.   In fact, I thought it was overly explicit mostly for the human reader (i.e. so they'd understand _all_ the arguments that could be called)

**Comment by rcastleman** [comment]
Actually ... all of those variables are set out at the top ... so I guess they can be eliminated!
