### ISSUE TITLE
several suggestions for cleaning up + scaling

### ISSUE THREAD

**Issue by thomascastleman** [rcastleman/monte_carlo#4]
Here's my recommendation for scaling to handle an arbitrary number of companies + eliminate redundancy in the code.

### `Company` class
Let's introduce a `Company` class which manages the data for a single company. A class like this allow us to create *objects* which represent each company. This can go somewhere near the top, maybe after the `# SIMULATION` comment:
```python
class Company:
    def __init__(self):
        self.initial_investment = None
        self.capital_out = None 
        self.inv_date = None
        self.exit_date = None
```
Use the following line at the beginning of `dcf_simulation` to create a list of companies in which we'll store the data computed by this round of simulation:
```python
# Create all company objects
companies = [Company() for _ in range(num_companies)]
```

### Turn repeated code into loops
Instead of repeating the computation for capital out, for instance, compute it in a loop. Indeed, we should do this for all of the things we're computing (`initial_investment`, `capital_out`, `inv_date`, and `exit_date`), but it probably makes most sense to have just one loop that loops over all companies and computes these four for each. 

You can start with this general template:
```python
for company in companies:
    company.initial_investment = ...
    company.capital_out = ...
    company.inv_date = ...
    company.exit_date = ...
```
(Hint: the expressions you're currently assigning to things like `company1_capital_out` are what should go in the `...`s) Just remember to compute using the *current* company's data--for instance, the `exit_date` should be computed as an offset from `company.inv_date` which is the investment start date of the current company.

This would also be a good place to add a comment above each field you set, explaining how it is computed (e.g. "The capital out is a multiple of the initial investment determined by a log-normal distribution centered at 1").

### Separate Excel I/O from the core computation

Notice in the above loop, there's no `model.range(...).value` to write/read from the Excel sheet. This is intentional--I think it's best to decouple setting up the data for the simulation and writing it to the sheet to perform the MOIC/IRR calculation (this will also make it easier to migrate away from Excel later on).

Put the following constant out above the `dcf_simulation` function:
```python
# Row of the Excel sheet where the first company's data goes
COMPANIES_START_ROW = 16
```

Then inside `dcf_simulation`, below the loop which computes data for each company, we can have a second loop which writes to the Excel sheet, like so:
```python
for i in range(num_companies):
    row = COMPANIES_START_ROW + i 
    company = companies[i]

    model.range(f"C{row}").value = -company.initial_investment
    model.range(f"D{row}").value = company.capital_out
    model.range(f"E{row}").value = company.inv_date
    model.range(f"F{row}").value = company.exit_date
``` 

This eliminates much of the hard-coding of Excel cell numbers (which doesn't scale and leaves a lot of room for error). If you change the sheet layout, just remember to update the `COMPANIES_START_ROW` to its new position.

> Note: By negating the `initial_investment` here, I'm assuming you'll store the positive version in each `Company` object. You can do the other way around, just make sure it's consistent either way.

**Comment by rcastleman** [comment]
Love this! Can't wait to implement

**Comment by rcastleman** [comment]
In the list comprehension, is the underscore the same as a variable? 

`[Company() for _ in range(num_companies)]`

**Comment by thomascastleman** [comment]
Yep, underscore isn't special in Python but is convention for an unused, unnamed variable. You're welcome to replace it with `for i in range(...)` if you find that more readable.
