### ISSUE TITLE
eliminate return of `results`

### ISSUE THREAD

**Issue by thomascastleman** [rcastleman/monte_carlo#5]
https://github.com/rcastleman/monte_carlo/blob/9974a6d7f6bdb00314440965b688b24fb17d4e1c/monte_carlo_python.py#L252-L253

Since `append` will update the list of `results`, there's no need to return it from this function.

**Comment by rcastleman** [comment]
Really?  I thought a return statement was necessary -- otherwise the function would return None ... 

_If you don’t supply an explicit return statement with an explicit return value, then Python will supply an implicit return statement using None as a return value._  ([source](url))

**Comment by thomascastleman** [comment]
Ultimately, it depends how you plan to use `dcf_simulation`. It seemed like its purpose was going to be to run one round of simulation and append onto the results list (`append` modifies the list it is given), and since `results` is global, I don't see why it would need to return it.
