### ISSUE TITLE
Xlwings dependency

### ISSUE THREAD

**Issue by rcastleman** [rcastleman/monte_carlo#7]
@thomascastleman 

I moved the local_code directory out of Dropbox and back into user/randycastleman ... but the problem remains. 

When I run mc.py in VS Code, it errors:

<img width="1030" alt="Screen Shot 2022-01-03 at 1 27 29 PM" src="https://user-images.githubusercontent.com/3673987/147966147-d1f23a36-8376-4c4e-9fd6-70b13421e5c1.png">

When I open Terminal from inside Anaconda, the program appears to run ... however, the Excel sheet APPEARS unchanged, though it shows up in VS Code git as changed:

<img width="1325" alt="Screen Shot 2022-01-03 at 1 25 39 PM" src="https://user-images.githubusercontent.com/3673987/147966401-8cb4013c-fca5-4cf6-a470-8d6092d78026.png">

**Comment by thomascastleman** [comment]
Can you try 
```
pip install xlwings
```
from a terminal in the repo directory? Then try running it the same way.

**Comment by rcastleman** [comment]
no luck - somehow can't use pip

`randycastleman@Randys-Air monte_carlo_sim % ls
archive		formula.png	monte_carlo
randycastleman@Randys-Air monte_carlo_sim % cd monte_carlo 
randycastleman@Randys-Air monte_carlo % git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Portfolio_monte_carlo.xlsx

no changes added to commit (use "git add" and/or "git commit -a")
randycastleman@Randys-Air monte_carlo % pip install xlwings
zsh: command not found: pip
randycastleman@Randys-Air monte_carlo % `
<img width="572" alt="Screen Shot 2022-01-04 at 9 41 30 PM" src="https://user-images.githubusercontent.com/3673987/148152360-13656e5c-dd39-4df7-89f4-ca7fcee69993.png">

**Comment by thomascastleman** [comment]
Can you try to install `pip` using the [directions here](https://pip.pypa.io/en/stable/installation/) and then retry installing `xlwings`.

**Comment by rcastleman** [comment]
those directions didn't work ... but pip3 (per [here](https://stackoverflow.com/questions/42870537/zsh-command-cannot-found-pip)) may do the trick

**Comment by rcastleman** [comment]
ARGH! Now it doesn't find pandas ... there is clearly something more fundamental going on here ... 
<img width="566" alt="Screen Shot 2022-01-05 at 9 13 55 PM" src="https://user-images.githubusercontent.com/3673987/148317285-97e1a411-84b4-457c-a33a-759ad399e558.png">

**Comment by thomascastleman** [comment]
That's promising, try
```
pip3 install pandas
```
and likewise with `numpy` and `matplotlib` as needed.

**Comment by rcastleman** [comment]
yes - it occurred to me last night that all these dependencies may have worked flawlessly using Jupyter notebooks generated by the Anaconda package, but for some reason they're not available when I'm operating out of VS Code ... so perhaps they must all be installed separately.  (It seems odd that they aren't available once they are on one's local machine, but perhaps there is a reason for that.)

**Comment by thomascastleman** [comment]
Yeah, I think the reason for that is exactly the reason for having "virtual environments" -- to keep different versions of different dependencies separate across projects.

**Comment by rcastleman** [comment]
Upgraded to pip3 and installed dependencies.  mc.py runs in terminal ... even opens the Excel file, as hoped ... though nothing appears to happen when the program runs ... back to debugging ... :-)

**Comment by rcastleman** [comment]
RESOLVED!! Thank you!
